default[:gifsicle][:install_prefix] = '/usr/local'
default[:gifsicle][:build_prefix] = '/usr/src'
default[:gifsicle][:version] = '1.71'
default[:gifsicle][:source_url] = 'http://www.lcdf.org/gifsicle/gifsicle-1.71.tar.gz'
default[:gifsicle][:source_sha256] = 'bdda2a444c31'
